// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(robot) {
    return robot.hear(/.*/i, function(context) {
      return robot.logger.info(context.message.text);
    });
  };

}).call(this);
